/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface ZProductCard {
      'product': any;
    }
  }

  interface HTMLZProductCardElement extends StencilComponents.ZProductCard, HTMLStencilElement {}

  var HTMLZProductCardElement: {
    prototype: HTMLZProductCardElement;
    new (): HTMLZProductCardElement;
  };
  interface HTMLElementTagNameMap {
    'z-product-card': HTMLZProductCardElement;
  }
  interface ElementTagNameMap {
    'z-product-card': HTMLZProductCardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'z-product-card': JSXElements.ZProductCardAttributes;
    }
  }
  namespace JSXElements {
    export interface ZProductCardAttributes extends HTMLAttributes {
      'onProductLiked'?: (event: CustomEvent) => void;
      'product'?: any;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;